Zadanie zbieżność - Świderski.md
PrzeChoj/2024Lato-WarsztatyBadawcze pull request #10
Opened 2024-03-01 11:00 UTC by PawelSwiderski1

Paweł Świderski zgłasza się do zadania Zbieżność

2024-03-01 15:32 UTC, PrzeChoj requested changes
Proszę wpisać swoje nazwisko pod (2)

2024-03-04 15:55 UTC, PawelSwiderski1 commented
Zmieniłem nazwę pull requesta, nie wiem czy o to chodziło

2024-03-05 21:13 UTC, PrzeChoj commented
A pliku jest miejsce na nazwisko osoby zgłoszonej do rozwiązania zadania. Znajduje się na górze pliku przy (2).

2024-03-05 21:44 UTC, PawelSwiderski1 commented
A dobra już widzę, wpisałem się tam w nowym commicie

2024-03-06 16:52 UTC, merged